# 将此配置文件复制到 ~/.aerospace.toml
# 之后，您可以根据自己的喜好编辑 ~/.aerospace.toml

# 不需要将所有键都复制到您的配置中。
# 如果您的配置中缺少某个键，"default-config.toml" 将作为后备

# 您可以使用它来添加在登录到 macOS 用户会话后运行的命令。
# 'start-at-login' 需要设置为 'true' 才能使 'after-login-command' 生效
# 可用命令：https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# 您可以使用它来添加在 AeroSpace 启动后运行的命令。
# 'after-startup-command' 在 'after-login-command' 之后运行
# 可用命令：https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    # JankyBorders 内置了对已运行进程的检测，
    # 因此在 AeroSpace 重启时不会重复运行
    # 'exec-and-forget sketchybar',
    # 'exec-and-forget borders',
]

# 通知 Sketchybar 关于工作区变化
# exec-on-workspace-change = ['/bin/bash', '-c',
#   'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
# ]
exec-on-workspace-change = []

# 在登录时启动 AeroSpace
start-at-login = false

# 标准化设置。参见：https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = false

# 参见：https://nikitabobko.github.io/AeroSpace/guide#layouts
# 'accordion-padding' 指定手风琴布局的填充大小
# 您可以设置为 0 来禁用填充功能
accordion-padding = 0

# 可能的值：tiles|手风琴
# 默认根容器布局
default-root-container-layout = 'accordion'

# 可能的值：horizontal|vertical|auto
# 'auto' 意味着：宽屏幕（宽度大于高度）获得水平方向，
#               高屏幕（高度大于宽度）获得垂直方向
#default-root-container-orientation = 'horizontal'
default-root-container-orientation = 'vertical'

# 可能的值：(qwerty|dvorak)
# 参见 https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# 当焦点显示器变化时，鼠标跟随焦点
# 如果您不喜欢这种行为，请从您的配置中删除它
# 参见 https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# 参见 https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# 窗口之间（inner-*）和显示器边缘（outer-*）之间的间隔。
# 可能的值：
# - 常量：     gaps.outer.top = 8
# - 按显示器：  gaps.outer.top = [{ monitor.main = 16 }, { monitor."某模式" = 32 }, 24]
#                 在这个例子中，24 是当没有匹配时的默认值。
#                 显示器模式与 'workspace-to-monitor-force-assignment' 相同。
#                 参见：https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors

[gaps]
inner.horizontal = 2
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

# 'main' 绑定模式声明
# 参见：https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' 绑定模式必须始终存在
# 所有可能的键：
# - 字母键：        a, b, c, ..., z
# - 数字键：        0, 1, 2, ..., 9
# - 小键盘数字键： keypad0, keypad1, keypad2, ..., keypad9
# - F键：         f1, f2, ..., f20
# - 特殊键：   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - 小键盘特殊键： keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - 方向键：         left, down, up, right
# 所有可能的修饰键： cmd, alt, ctrl, shift
# 所有可能的命令：https://nikitabobko.github.io/AeroSpace/commands
# 参见：https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# 您可以取消下面的注释，使用 alt + enter 快捷键打开终端（如同在 i3 中）
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

[mode.main.binding]
# 禁用“隐藏应用程序”
cmd-h = []

# i3 风格
# alt-h = 'split horizontal'
# alt-v = 'split vertical'
alt-f = 'fullscreen'
alt-s = 'layout v_accordion' # i3 中的 'layout stacking'
alt-w = 'layout h_accordion' # i3 中的 'layout tabbed'
# alt-e = 'layout tiles horizontal vertical' # i3 中的 'layout toggle split'
alt-shift-space = 'layout floating tiling'

# 参见：https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion vertical horizontal'
# alt-comma = 'layout accordion vertical'
# alt-comma = 'layout accordion horizontal'

# 参见：https://nikitabobko.github.io/AeroSpace/commands#focus
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

# 参见：https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# 参见：https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# 参见：https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 0'

# 移动当前聚焦的窗口到指定工作区，并切换到该工作区
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-0 = ['move-node-to-workspace 0', 'workspace 0']

# 参见：https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
# 将 alt-shift 配置放入 skhd

# 参见：https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
# 参见：https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
# alt-tab = 'workspace-back-and-forth'
# alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# 参见：https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# 'service' 绑定模式声明。
# 参见：https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # 重置布局
b = ['balance-sizes', 'mode main'] # 重置布局
#s = ['layout sticky tiling', 'mode main'] # sticky 功能尚未支持 https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main']
c = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

####################################
[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
if.window-title-regex-substring = '^(?!WeChat \(Chats\)|微信 \(聊天\)).*$'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = '(setting|设置)'
run = ['move-node-to-workspace 9']

[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.kmcnjdcipmgchfndpapkoecbidofdpbc'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = '(Picture-in-Picture|画中画)'
run = 'layout floating'

# Workspace 0: 企业微信, iOA, 酷狗音乐
[[on-window-detected]]
if.app-id = 'com.tencent.WeWorkMac'
run = ['move-node-to-workspace 0']

[[on-window-detected]]
if.app-id = 'com.tencent.iOA'
run = ['move-node-to-workspace 0']

[[on-window-detected]]
if.app-id = 'com.kugou.mac.Music'
run = ['move-node-to-workspace 0']

# Workspace 1: Cursor
[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = ['move-node-to-workspace 1']

# Workspace 2: Windsurf
[[on-window-detected]]
if.app-id = 'com.exafunction.windsurf'
run = ['move-node-to-workspace 2']

# Workspace 3: Chrome
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['move-node-to-workspace 3']

# Workspace 4: Ghostty
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['move-node-to-workspace 4']

# Workspace 5: WeTerm
[[on-window-detected]]
if.app-id = 'com.tencent.weterm'
run = ['move-node-to-workspace 5']

# Workspace 6: QSpace
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['move-node-to-workspace 6']

# Workspace 7: Obsidian
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['move-node-to-workspace 7']

# Workspace 8: TencentMeeting
[[on-window-detected]]
if.app-id = 'com.tencent.meeting'
run = ['move-node-to-workspace 8']

# Workspace 9: Monitor
[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = ['move-node-to-workspace 9']
