# ---------------------- oh-my-zsh ----------------
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="fox"

# clone 在 -(~/.oh-my-zsh/custom/plugins)-[git://master ✗] - 中
# ├── example
# ├── zsh-autosuggestions
# ├── zsh-syntax-highlighting
# └── zsh-vi-mode

plugins=(git zsh-syntax-highlighting zsh-autosuggestions docker zsh-vi-mode)

# 改变 history 和 dump文件 的位置
HISTFILE="${ZSH}/cache/.zsh_history"
ZSH_COMPDUMP="${ZSH}/cache/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"

source $ZSH/oh-my-zsh.sh

# --------------------- zsh -----------------------
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=blue'

# --------------------- general -------------------
export TERM="xterm-256color"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LS_COLORS=${LS_COLORS}:'di=01;35'

#  --------------------- alias --------------------
alias "nv"="nvim"
alias "tm"="tmux"
alias "ll"="ls -l"
alias "la"="ls -al"
alias "fd"="fdfind"

# ------------------ editor ----------------------
export EDITOR=vim
export VISUAL=vim

# ------------------ nvim ----------------------- [非包管理器安装的需要此配置]
export PATH="$PATH:/opt/nvim-linux64/bin"

#------------------- leetgo -------------------
export PATH="$PATH:/home/zq/Leetgo/bin/"

#------------------- maven -------------------
export MAVEN_HOME=/opt/apache-maven-3.2.5
export PATH=$MAVEN_HOME/bin:$PATH

#------------------- proxy -------------------
function pon() {
    local proxy_ip_address="127.0.0.1"
    local port="7890"

    if [[ -n "$1" ]]; then
        proxy_ip_address="$1"
    fi

    if [[ -n "$2" ]]; then
        port="$2"
    fi

    export http_proxy="http://${proxy_ip_address}:${port}"
    export https_proxy="http://${proxy_ip_address}:${port}"
    export all_proxy="socks5://${proxy_ip_address}:${port}"
    echo -e "proxy on, ip is ${proxy_ip_address}, port is ${port}"
    echo -e "please wait for 3 seconds to test..."

    local google_result=$(curl -s --connect-timeout 3 -m 3 www.google.com)
    if [[ -z "${google_result}" ]]; then
        echo -e "proxy on failed, please check it."
        return 1
    else
        echo -e "proxy on success.🚀️🚀️🚀️"
        echo -e "your curl google's data length is: ${#google_result}"
        return 0
    fi
}

function poff() {
    unset http_proxy
    unset https_proxy
    unset all_proxy
    echo -e "proxy turn off🌙️"
    curl cip.cc
    return 0
}

## -------------------------- auto gens  -----------------------

# ------------------ pnpm [auto gen] -----------------------
export PNPM_HOME="/home/zq/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# ------------------ node version manage [auto gen] ----------------------
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# ------------------ conda [auto gen] ----------------------
__conda_setup="$('/home/zq/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/zq/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/zq/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/zq/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# ------------------ golang version manager [auto gen] ----------------------
[[ -s "/home/zq/.gvm/scripts/gvm" ]] && source "/home/zq/.gvm/scripts/gvm"

#------------------- fuzzy-shell [auto gen] -------------------
source "${HOME}/.fuzzy_shell/scripts/export.sh"
alias "fs"="fuzzy --search"
alias "fj"="fuzzy --jump"
alias "fe"="fuzzy --edit"
alias "hh"="fuzzy --history"
